title: Niri
email: rokhim.whd@gmail.com
description: Niri Jekyll Theme Blog using Bulma
baseurl: "" 
url: "" 
twitter_username: rokhiminwahid
github_username:  rokhimin
theme: niri
logo: https://i.ibb.co.com/sdVSmQ5x/niri-logo.png 